package com.esignal.MicrolifeTester;

import java.util.UUID;


public class Uuid
{
    private UUID UUID_UPDATE_CODE_SERVICE = UUID.fromString("0000fff0-0000-1000-8000-00805f9b34fb");
    private UUID UUID_RESP_INDICATION_CHARACTERISTIC = UUID.fromString("0000fff1-0000-1000-8000-00805f9b34fb");
    private UUID UUID_WRITE_CODE_REQUEST_CHARACTERISTIC = UUID.fromString("0000fff2-0000-1000-8000-00805f9b34fb");

    public UUID getUUID_UPDATE_CODE_SERVICE()
    {
        return UUID_UPDATE_CODE_SERVICE;
    }

    public UUID getUUID_RESP_INDICATION_CHARACTERISTIC()
    {
        return UUID_RESP_INDICATION_CHARACTERISTIC;
    }

    public UUID getUUID_WRITE_CODE_REQUEST_CHARACTERISTIC()
    {
        return UUID_WRITE_CODE_REQUEST_CHARACTERISTIC;
    }

    public void setUUID_UPDATE_CODE_SERVICE(UUID UUID_UPDATE_CODE_SERVICE)
    {
        this.UUID_UPDATE_CODE_SERVICE = UUID_UPDATE_CODE_SERVICE;
    }

    public void setUUID_RESP_INDICATION_CHARACTERISTIC(UUID UUID_RESP_INDICATION_CHARACTERISTIC)
    {
        this.UUID_RESP_INDICATION_CHARACTERISTIC = UUID_RESP_INDICATION_CHARACTERISTIC;
    }

    public void setUUID_WRITE_CODE_REQUEST_CHARACTERISTIC(UUID UUID_WRITE_CODE_REQUEST_CHARACTERISTIC)
    {
        this.UUID_WRITE_CODE_REQUEST_CHARACTERISTIC = UUID_WRITE_CODE_REQUEST_CHARACTERISTIC;
    }
}
